### ISSUE TITLE
A type with the same name was already loaded, from a different assembly. Type failing: Starcounter.Authorization.Database.PermissionToken

### ISSUE THREAD

**Issue by habib535** [Starcounter/authorization#62]
Run any two apps simultaneously that are using `Starcounter.Authorization` library and the host database crashes with the following message.

```
Starcounter.DbException: ScErrTypeAlreadyLoaded (SCERR4274): A type with the same name was already loaded, from a different assembly. Type failing: Starcounter.Authorization.Database.PermissionToken, (Starcounter.Authorization, Version=1.2.0.0). Already loaded: Starcounter.Authorization.Database.PermissionToken, (Starcounter.Authorization, Version=1.1.0.0) Version: 2.3.1.6886. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4274. 
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\TeamCity\BuildAgent\work\sc-6932\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 180
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\BuildAgent\work\sc-6932\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\BuildAgent\work\sc-6932\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-6932\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=4274
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4274
```

Currently there are only three apps that are using Starcounter.Authorization

1. Images
2. Calender
3. Search

To reproduce this error, at least one of the app needs to be installed/started via the warehouse. If both are started from visual studio then they works fine.

It is hard to put a debugger in the app or Authorization library because the error happens before execution enters the entry point e.g. `main method`

**Comment by habib535** [comment]
@mmnosek  @warpech

**Comment by warpech** [comment]
Perhaps the Authorization library needs to be in `weaver.ignore`?

If not, then I guess this is because the library is not in the same version in all apps

**Comment by habib535** [comment]
Yes it was library version mismatch. Downgrading to previous version in Search app worked. I will deploy with the old version for now but I will create an issue where we need to update Authorization library in all app simultaneously and deploy them but the ideal scenario would be to make them work together with different versions.

**Comment by mmnosek** [comment]
> the ideal scenario would be to make them work together with different versions.

Unfortunately, it's not only Authorization Library issue. Using different versions of the same assembly is currently a huge pain in Starcounter and I think it could be fixed only with incoming hosting model change. If we'll have a separate process for each app, every app will be able to use a different version of the same assembly.

**Comment by warpech** [comment]
Can you find an issue about that in one of the core repos? Then this can be cross-linked and closed.

**Comment by habib535** [comment]
https://github.com/Starcounter/level1/issues/3872
