### ISSUE TITLE
Two apps having the Authorization library can't run under the same database

### ISSUE THREAD

**Issue by habib535** [Starcounter/authorization#68]
In `HeadsOmni` repo we are using Authorization library in `EcsterPay` and `Orders` app. When you try to run both the first app will start but second fails with the following error. Try executing EcsterPay first and Orders app will throw this error, if Orders app is executed first then EcsterPay will throw the same error.

```
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Starcounter.Startup.Routing.RouterServiceCollectionExtensions.AddRouter(Microsoft.Extensions.DependencyInjection.IServiceCollection, Boolean)'.
   at EcsterPayConnector.Startup.ConfigureServices(IServiceCollection services)
   at Starcounter.Startup.DefaultStarcounterBootstrapper.Start(IStartup application)
   at EcsterPayConnector.Program.Main() in D:\Workspace\HeadsOmni\src\EcsterPayConnector\EcsterPayConnector\Program.cs:line 19
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\  c_work\sc-19252\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 553
Version: 2.4.990.127.
Help page: https://docs.starcounter.io/?q=SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\  c_work\sc-19252\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 587
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\  c_work\sc-19252\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 278
   at Starcounter.Hosting.Package.Process() in C:\      c_work\sc-19252\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 140
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\       c_work\sc-19252\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 54
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\ c_work\sc-19252\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Processor.cs:line 90
ErrorCode=4259
HResult=-2146233088
HelpLink=https://docs.starcounter.io/?q=SCERR4259
---> System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Starcounter.Startup.Routing.RouterServiceCollectionExtensions.AddRouter(Microsoft.Extensions.DependencyInjection.IServiceCollection, Boolean)'.
   at EcsterPayConnector.Startup.ConfigureServices(IServiceCollection services)
   at Starcounter.Startup.DefaultStarcounterBootstrapper.Start(IStartup application)
   at EcsterPayConnector.Program.Main() in D:\Workspace\HeadsOmni\src\EcsterPayConnector\EcsterPayConnector\Program.cs:line 19
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\  c_work\sc-19252\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 553
HResult=-2146233069
```

**Comment by joozek78** [comment]
I think it's a problem of https://github.com/Starcounter/level1/issues/3872. Did you make sure you reference the same `Starcounter.Startup` version in both apps?

**Comment by habib535** [comment]
Thanks @joozek78 different versions of `Starcounter.Startup` was the reason.
