### ISSUE TITLE
Starcounter.Authorization is not compatible with 2.4.0.7170

### ISSUE THREAD

**Issue by miyconst** [Starcounter/authorization#88]
Trying to start an app referencing `Starcounter.Authorization 3.7.5` results in the following error:

```
"System.MissingMethodException: Method not found: 'Void Starcounter.Scheduling.ScheduleTask(System.Action, Boolean, Byte)'.
   at Starcounter.Authorization.Authentication.CleanupStartupFilter`1.CleanUp(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
HResult=-2146233069
"
```

**Comment by miyconst** [comment]
The fix is available in the [`3.7.6`](https://github.com/Starcounter/Starcounter.Authorization/releases/tag/3.7.6) release.
